services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: etudiant
      POSTGRES_PASSWORD: motdepasse_tp5
      POSTGRES_DB: ecole
    volumes:
      - pgdata_tp5:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U etudiant -d ecole"]
      interval: 5s
      timeout: 5s
      retries: 12
    networks: [backend]

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redisdata_tp5:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks: [backend]

  web:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      POSTGRES_USER: etudiant
      POSTGRES_PASSWORD: motdepasse_tp5
      POSTGRES_DB: ecole
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PORT: 3000
    ports:
      - "5002:3000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "node -e \"fetch('http://localhost:3000/health').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))\""]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 15s
    networks: [backend]

  adminer:
    image: adminer:4
    ports:
      - "8085:8080"
    depends_on:
      db:
        condition: service_healthy
    networks: [backend]

volumes:
  pgdata_tp5:
  redisdata_tp5:

networks:
  backend:
    driver: bridge
